/**
 * Bridge that carries platform tools onto an engine-driven route.
 *
 * WHY. On a subscription route the loop is driven by the Claude Code engine,
 * and the model's tool registry is the engine's own. Platform plugin tools do
 * not reach the model AT ALL: the platform has an MCP client but no MCP server
 * of its own (established 2026-08-22, confirmed by two independent readings —
 * zero tool/* events in the platform log, while the actual calls appear only in
 * the engine transcript). The bridge gives platform tools the same path that
 * tools of external MCP servers arrive by.
 *
 * SHAPE. Three parts in three processes:
 *   1. THIS plugin — inside the platform process. Owns a loopback entry point
 *      and executes calls. Goal state lives here too, which is why execution
 *      belongs here and not in the gateway.
 *   2. provider adapter — tells the gateway the identity of the live agent and
 *      the address of that entry point, on every request.
 *   3. subscription gateway — assembles an MCP server (sdk transport) and hands
 *      it to the engine.
 * The gateway knows nothing about goals: it receives the tool DESCRIPTION from
 * here and proxies calls back. That is a requirement of a general solution —
 * the next agent, with a different tool set, connects without editing the
 * gateway.
 *
 * 🔴 WHAT IS NOT REIMPLEMENTED HERE. Identity resolution, argument validation
 * and result validation are the platform's own; ctx.typertGateway (the
 * platform's remote boundary) does them. Operation schemas are generated by the
 * platform and live in each package's typert.host.js. The bridge neither
 * duplicates nor weakens them: on a made-up identity the boundary refuses
 * ("lookup provider \"agent\" did not resolve the requested identity"), verified
 * by a live run on 2026-08-22.
 *
 * 🔴 A BOUNDARY YOU MUST KNOW. Only MUTATING goal operations are exposed across
 * the remote boundary (clear, complete, create, edit, pause, resume). There are
 * no reads there at all: goals/get answers "no active Remote method exports
 * this endpoint". So the reading tool is executed by a direct service call in
 * this same process — and that is the only place where the bridge acts around
 * the boundary. There is not a single mutating operation around it.
 *
 * ACCESS BOUNDARIES. The entry point listens on loopback (127.0.0.1) only and
 * requires a ONE-TIME TICKET — not a shared secret. The ticket is born here for
 * a pair (identity, turn), travels to the gateway in the adapter's response
 * body, lives in the closure of the server instance and dies on turn/end of its
 * own turn. Identity is NEVER SENT over the gateway→bridge wire: the bridge
 * looks it up in its own table by ticket, so the caller has nothing to assert
 * an identity with.
 * 🔴 HISTORY, so that this header does not drift from the code again: until
 * 10:03 on 2026-08-22 there was a LONG-LIVED shared secret here, and identity
 * travelled as a separate field. That design is gone; its description outlived
 * the code by several hours, and a wrong conclusion about the design was drawn
 * from the description. If you change the design, fix this paragraph in the
 * same pass.
 * The ticket never reaches a command line: the sdk transport spawns no child
 * process, and everything the SDK passes as an argument (--mcp-config) is
 * readable by any user of the machine through /proc/<pid>/cmdline (mode 444) —
 * verified with a live observer on 2026-08-22.
 */
import { createServer } from 'node:http'
import { randomBytes } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import z from '@deepseek-ai/schemastery'

export const name = 'dsh-tool-bridge'
export const inject = ['agents', 'goals', 'typertGateway', 'jobs']

export const Config = z.object({
  /** Loopback entry-point port. Zero — take a free one and report it to the adapter. */
  port: z.number().default(0),
  /** Domains the bridge exposes to the model. One for now; a list, to grow. */
  domains: z.array(z.string()).default(['goals']),
  /**
   * Goal-creation ceiling: how many per agent per window.
   * 🔴 Deliberately WITHOUT .default(): the default value would coincide with
   * ours, and then the startup line could not tell "the config arrived" from
   * "the field was lost". What tells them apart is the presence of the key, so
   * the default is resolved in code instead.
   */
  createLimit: z.number(),
  /** Sliding window length for the ceiling, in minutes. Fractions allowed (for the test bench). */
  createWindowMinutes: z.number(),
  /**
   * Threshold for action blocked — how many autonomous rounds must have passed.
   * Must match blockedAfterConsecutiveRounds in dsh-tool-goal: otherwise one and
   * the same prohibition behaves differently on the two routes.
   */
  blockedAfterRounds: z.number(),
  /**
   * Upper lifetime of a ticket, in minutes. Insurance for the case where
   * turn/end never arrives at all (the process is alive but the turn hung):
   * without a deadline a "one-time" ticket would degenerate into a long-lived
   * password. The number is deliberately larger than the longest turn ever
   * observed — cutting tools off mid-work is worse than holding a ticket an
   * extra hour.
   */
  ticketTtlMinutes: z.number(),
  /**
   * MCP server name. It becomes the PREFIX of every tool name the model sees
   * (mcp__<name>__create_goal) and of the ban list for subagents, therefore:
   *   — it is your own, not a generic word: a generic one will eventually
   *     collide with somebody else's server, and on collision ours is silently
   *     shadowed (naming rule, 2026-08-22);
   *   — it does NOT coincide with server names on other levels (other MCP
   *     servers, probes).
   * 🔴 Deliberately without .default() — for the same reason as the numbers above.
   */
  serverName: z.string(),
  /**
   * 🔴 SELF-WAKE STOP LIMIT — the five fields below. The reasoning behind these
   * particular numbers: while alarms are one-shot the mechanism is safe; the
   * first RECURRING reminder turns it into a guard without a boundary, which
   * burns quota when nobody is around.
   * All of them are deliberately WITHOUT .default() — same reason as above.
   */
  /** Minimum interval allowed for a recurring reminder, in seconds. Our limit on top of theirs. */
  heartbeatMinIntervalSeconds: z.number(),
  /** How many autonomous wake-ups in a row are allowed without a word from a human. */
  heartbeatMaxConsecutive: z.number(),
  /** How many wake-ups per day are allowed PER SESSION. */
  heartbeatMaxPerDay: z.number(),
  /** The zone the day is counted in. */
  heartbeatDayZone: z.string(),
  /** Where to put the stop notice. The exchange directory is defined by your messaging module. */
  heartbeatNoticeDir: z.string(),
  /**
   * Message source kinds that count as a word from a live human. See
   * HEARTBEAT_HUMAN_KINDS_DEFAULT: 'user' exists everywhere, the rest are
   * introduced by whichever module receives messages on your build.
   */
  heartbeatHumanKinds: z.array(z.string()),
})

/**
 * Default server name. Not 'dsh': a generic word risks colliding with someone
 * else's. Base tool names stay literally the platform's own (create_goal,
 * get_goal, …) — the prefix is added by the protocol, not by us.
 */
const SERVER_NAME_DEFAULT = 'bridge'

/** Ceiling defaults. An operational decision: three creations per sliding hour. */
const CREATE_LIMIT_DEFAULT = 3
const CREATE_WINDOW_MINUTES_DEFAULT = 60
/**
 * Default blocked threshold.
 *
 * 🔴 THIS IS A CONSTANT DUPLICATED ACROSS A BOUNDARY WE DO NOT CONTROL.
 * The number is taken from the platform: @deepseek-ai/dsh-tool-goal,
 * lib/index.js — line 109 (`blockedAfterConsecutiveRounds:
 * z.number().step(1).min(1).default(3)`) and line 194
 * (`config.blockedAfterConsecutiveRounds ?? 3`). Read off package version
 * 0.1.1-rc.2 (2026-08-22).
 *
 * It is repeated here because action=blocked goes through OUR direct call: the
 * block method is not exposed across the remote boundary, so that path does not
 * pass the platform's own check. Without the repetition, one and the same
 * prohibition would behave differently on the two routes.
 *
 * RE-CHECK IT WHEN YOU UPGRADE THE PLATFORM — the platform will change its
 * number at home and ours will silently diverge. One command:
 *     tools/check-blocked-threshold.sh
 * The same command is the healthcheck of the dsh-tool-bridge entry in the
 * plugin registry.
 */
const BLOCKED_AFTER_ROUNDS_DEFAULT = 3
/** Upper ticket lifetime. Insurance against an aborted turn: without it a
 *  ticket would hang until the platform restarts. Six hours is safely longer
 *  than the longest turn and safely shorter than a day. */
const TICKET_TTL_MINUTES_DEFAULT = 360

/**
 * 🔴 SELF-WAKE STOP LIMIT DEFAULTS (an operational decision).
 *
 * 1800 s — no more often than twice an hour. The platform minimum of 300 s was
 * chosen for a different problem: five minutes is 288 turns a day. Our limit is
 * STRICTER than theirs, and that is a deliberate departure from "the bridge
 * repeats nothing": for schedule tools the bridge normally only delivers the
 * call to the native body, whereas here it adds a policy of its own. Said out
 * loud so the next reader does not take it for an accident.
 *
 * 6 in a row at a half-hour step — three hours of silence. Longer than that
 * means the human has not come back within any foreseeable time.
 *
 * 48 per day — 🔴 PER SESSION, NOT PER AGENT, and this must be read as a number,
 * not as a word. The counter is derived from the log of a SPECIFIC session, and
 * an agent may have several sessions (our installation has two: the owner
 * channel and a service one). So the agent's total ceiling equals 48 × the
 * number of live root sessions. Summing over agents.roots() was deliberately
 * NOT done: simple and working beats precise and brittle, and 96 a day is still
 * once every fifteen minutes around the clock.
 */
const HEARTBEAT_MIN_INTERVAL_SECONDS_DEFAULT = 1800
const HEARTBEAT_MAX_CONSECUTIVE_DEFAULT = 6
const HEARTBEAT_MAX_PER_DAY_DEFAULT = 48
const HEARTBEAT_DAY_ZONE_DEFAULT = 'Europe/Moscow'
/**
 * Where to put the stop notice.
 *
 * 🔴 THE DEFAULT IS EMPTY, AND THAT IS NOT A FORGOTTEN FIELD. An exchange
 * directory exists only on an installation that has a messaging module;
 * inventing a path on its behalf would mean writing files where nobody reads
 * them. Empty means "the notice goes to the log only" — and it goes to the log
 * ALWAYS, in full, including when a directory is set. There is no silent
 * outcome at all.
 */
const HEARTBEAT_NOTICE_DIR_DEFAULT = ''

const log = (m) => console.error(`[tool-bridge] ${m}`)

/**
 * 🔴 PARITY WITH THE NATIVE-ROUTE TOOL SET (an installation-owner requirement).
 *
 * Names, descriptions and parameter schemas ARE NOT WRITTEN HERE BY HAND. They
 * live in parity.json, which is generated by EXECUTING the platform packages
 * (@deepseek-ai/dsh-tool-goal and dsh-tool-jobs) through the generator
 * tools/extract-parity.mjs: a stand-in ctx collects whatever those packages
 * register on the native route. That is why "character for character" is
 * provable here rather than merely asserted: a divergence is possible only if
 * the packages themselves diverge, and regenerating the file catches it.
 *
 * WHAT IS STILL OURS — only EXECUTION (the EXEC table below). It has to be
 * ours: on the native route a tool calls a service inside its own process,
 * whereas our call arrives from another route and must cross the platform
 * boundary.
 */
const PARITY = JSON.parse(
  readFileSync(new URL('./parity.json', import.meta.url), 'utf8'),
)

/**
 * 🔴 SCHEDULE — A SECOND SOURCE, AND IT IS SEPARATE ON PURPOSE.
 *
 * schedule.json is generated by EXECUTING the platform package
 * @deepseek-ai/dsh-schedule through tools/extract-schedule.mjs — the same
 * technique that produces parity.
 *
 * WHY IT IS NOT APPENDED TO parity.json. The word "parity" here means exactly
 * one thing: "character for character with the native-route tool set", and that
 * is proved by checking against ITS live packages. There is no schedule on the
 * native route. Appending it to the same file would break both the meaning of
 * the word and the check that backs it. Here the parity is with a different
 * subject — with a platform package mounted on our side.
 *
 * HOW THIS LAYER DIFFERS AT EXECUTION TIME: goals and jobs the bridge executes
 * itself (platform boundary, or a service), whereas schedule it does NOT
 * execute. It calls the native tool body registered on the live agent. See EXEC.
 */
const SCHEDULE = JSON.parse(
  readFileSync(new URL('./schedule.json', import.meta.url), 'utf8'),
)

/**
 * The full set the bridge exposes. Order matters only for the readability of
 * the log line; names must be unique, and that is checked here rather than
 * assumed: an overlap between the two sources would silently take one tool away
 * from the model while the log line still showed the right count.
 */
const TOOLS = [...PARITY, ...SCHEDULE]
{
  const seen = new Set()
  for (const t of TOOLS) {
    if (seen.has(t.name)) throw new Error(`tool-bridge: name "${t.name}" occurs twice in the tool set`)
    seen.add(t.name)
  }
}

/**
 * 🔴 THERE IS NO SCHEMA CONVERTER HERE, AND THAT IS NOT AN OMISSION. The
 * platform's defineTool normalises parameters into a finished JSON Schema at
 * registration time — that is, parity.json already holds exactly what the
 * engine expects. The first version of the bridge converted that schema a
 * second time and SILENTLY lost everything: the converter received
 * {type:'object',properties:…} while it expected {name:{…}}, so the action enum
 * and the required fields disappeared and the schema stayed syntactically
 * valid. The test bench caught it on an enum check. Any future converter here
 * is a reason to first prove it is needed.
 */

/**
 * Execution, keyed by parity names.
 *
 * `remote` — an operation of the platform's remote boundary (namespace/method).
 * Identity resolution, argument validation and result validation are done by
 * the boundary itself; the bridge neither duplicates nor weakens them.
 * `local` — a direct service call in this same process. Defined only where
 * there is NO boundary (verified against the Remote decorators in dsh-goal:
 * edit, pause, resume, complete, clear, create are exposed, while get and block
 * are NOT; the jobs service has no remote methods at all).
 * 🔴 The isolation of the local path rests not on a check of ours but on the
 * service itself: both goals.get and every jobs.* take a LIVE agent and work
 * only with its own state.
 */
/**
 * 🔴 THE TURN-AUTHORITY LAYER (an operational decision, layer 1 of three).
 *
 * WHY. The identity in a call answers "whose agent", not "by what right". An
 * engine subagent arrives with the root's identity (built-in types cannot have
 * the bridge server taken away from them — verified 2026-08-22), so what must
 * be distinguished is not the caller but the AUTHORITY OF THE TURN the call is
 * made inside: was the turn opened by a human, or by a round of the current
 * goal?
 *
 * 🔴 THIS REPRODUCES SOMEONE ELSE'S POLICY, IT IS NOT OUR OWN. It is copied
 * verbatim from @deepseek-ai/dsh-tool-goal (lib/types/authority.js of the same
 * installed version), together with its BOUNDARIES, not only its prohibitions:
 * where the native route does not require authority, it is not required here
 * either. Home-grown tightening breaks work exactly as much as loosening does:
 * an agent whose human just asked "so how is it going" must be able to answer
 * "I am stuck".
 *
 * WHAT CANNOT BE REPRODUCED, AND WHY. The original additionally requires
 * `ctx.agents.currentInitiator() === agent`. The initiator lives in the turn's
 * AsyncLocalStorage, and this handler is loopback HTTP — a different async
 * context, where there is no initiator at all (established 2026-08-21).
 * Therefore the check is written as "if an initiator IS visible and it is not
 * our agent — refuse": when it is available the policy is not weakened, and
 * when it is not, it does not produce a false refusal. The gap is closed by
 * agent liveness and by the open turn.
 */

/** The current turn's window: events after the last turn/start. Turn closed — refuse. */
function openTurn(agent) {
  const events = agent.session.events
  for (let i = events.length - 1; i >= 0; i -= 1) {
    const b = events[i]
    if (b?.type === 'turn/end') throw new Error('goal tools require an open model turn')
    if (b?.type === 'turn/start') return events.slice(i + 1)
  }
  throw new Error('goal tools require an open model turn')
}

/**
 * A live agent and its turn window. Instance identity, running state and an
 * open turn — the same three signs as on the native route, minus the initiator.
 */
function bridgeExecution(agents, agentId) {
  const agent = agents.get(String(agentId))
  if (!agent) throw new Error(`live agent "${agentId}" not found in the registry`)
  if (agent.status !== 'running') throw new Error(`agent "${agentId}" is not running (${agent.status})`)
  let initiator
  try { initiator = agents.currentInitiator() } catch { initiator = undefined }
  if (initiator !== undefined && initiator !== agent) {
    throw new Error('the call arrived outside the turn of the calling agent')
  }
  return { agent, events: openTurn(agent) }
}

/**
 * Human authority: a root agent and a human message inside this turn.
 * 🔴 Only kind === 'user' — verbatim as in the original. A service channel, if
 * you have one, carries ITS OWN source kind and does NOT grant human authority:
 * the right to dispose of a goal comes as a direct command to the host, and we
 * deliberately declined to give it a second, implicit path (an operational
 * decision).
 * 🔴 Separately: the self-wake limit uses a DIFFERENT list of kinds, and it is
 * configurable — see HEARTBEAT_HUMAN_KINDS_DEFAULT. There the question is "is
 * anybody alive nearby", here it is "is this allowed to dispose of the goal".
 * Different questions, different answers.
 */
function hasDirectHumanInput(agents, execution) {
  if (!agents.roots().includes(execution.agent)) return false
  return execution.events.some((e) => e.type === 'user/message' && e.data?.source?.kind === 'user')
}

/** The turn is exactly the admitted round of the current goal: goal, revision and number. */
function isMatchingGoalRound(execution, goal) {
  return execution.events.some((e) =>
    e.type === 'user/message'
    && e.data?.source?.kind === 'goal'
    && e.data.source.goalId === goal.id
    && e.data.source.revision === goal.revision
    && e.data.source.round === goal.roundsStarted)
}

/** create, edit, pause, resume — a direct human turn on the root, and nothing else. */
function requireDirectHuman(agents, execution) {
  if (hasDirectHumanInput(agents, execution)) return
  throw new Error('this operation requires a direct human turn on the root agent')
}

/** complete and blocked — a human OR exactly the current goal round. */
function completionAuthority(ctx, agents, execution) {
  if (hasDirectHumanInput(agents, execution)) return { kind: 'direct-human' }
  const goal = ctx.get('goals').get(execution.agent)
  if (goal !== undefined && isMatchingGoalRound(execution, goal)) return { kind: 'goal-round', goal }
  throw new Error('complete and blocked require a direct human turn or the current goal round')
}

/**
 * 🔴 CLAMPING THE ROUND LIMIT PASSED IN (an operational decision).
 *
 * THIS IS A DEPARTURE FROM PARITY, AND IT IS DELIBERATE — said out loud: the
 * native route has no such clamp. The reason is in the platform's shape: create
 * takes `request.maxGoalRounds ?? defaultMaxGoalRounds`, that is, WHAT THE MODEL
 * PASSES WINS over the configuration, and our limit of 5 rounds is removed by a
 * single argument. The tool schema stays at parity: the field is there, the type
 * is the same.
 *
 * THE BOUNDARY WHEN THE READ FAILS. The ceiling is taken from the live goals
 * service. If the field disappears (it belongs to the library, an upgrade may
 * remove it), the passed value is DISCARDED entirely — the goal gets the host
 * default. That is fail-closed in substance: the limit is not raised, and the
 * tool stays alive.
 */
function capRounds(ctx, requested) {
  if (requested === undefined) return undefined
  const cap = ctx.get('goals')?.resolved?.defaultMaxGoalRounds
  if (typeof cap !== 'number') {
    log(`🔴 host round limit could not be read — the passed value ${requested} was discarded`)
    return undefined
  }
  if (requested > cap) {
    log(`round limit clamped: requested ${requested}, host ceiling ${cap}`)
    return cap
  }
  return requested
}

const EXEC = {
  get_goal: {
    /**
     * Requires no authority — same as on the native route: reading one's own
     * state. But it does require an open turn: goalToolExecution is called here too.
     */
    authority: 'turn',
    local: (ctx, agent) => ctx.get('goals').get(agent) ?? null,
  },
  create_goal: {
    /** requireDirectHuman — verbatim from dsh-tool-goal. */
    authority: 'human',
    remote: {
      namespace: 'goals',
      method: 'create',
      build: (a, ctx) => ({
        request: {
          objective: a.objective,
          ...(capRounds(ctx, a.max_goal_rounds) === undefined
            ? {}
            : { maxGoalRounds: capRounds(ctx, a.max_goal_rounds) }),
        },
      }),
    },
    /** The only tool under the ceiling: it alone can produce a runaway. */
    counted: true,
  },
  /** Authority depends on the action — resolved inside. */
  update_goal: { authority: 'dispatch', dispatch: updateGoal },
  job_list: {
    authority: 'none',
    local: (ctx, agent) => ctx.get('jobs').list(agent),
  },
  job_output: {
    authority: 'none',
    local: (ctx, agent, a) => ctx.get('jobs').read(String(a.job_id), agent),
  },
  job_kill: {
    authority: 'none',
    local: (ctx, agent, a) => ctx.get('jobs').kill(String(a.job_id), agent, a.reason),
  },

  /**
   * 🔴 SCHEDULE: THE NATIVE BODY EXECUTES, THE BRIDGE REPEATS NOTHING.
   *
   * For goals and jobs the bridge must execute itself: on the native route the
   * tool calls a service inside its own process, while our call arrives from
   * another route. Schedule has no such need: the dsh-schedule package
   * registers its three tools DIRECTLY ON OUR LIVE AGENT (verified 2026-08-22:
   * all three are visible in the request/header of the live session). They fail
   * to reach the model only because the engine substitutes its own tool set —
   * that is, DELIVERY is lost, not execution. So the correct cure is to deliver
   * the call to the native body, not to rewrite it. Neither policy, nor argument
   * validation, nor session-log work belongs here: the tool does all of that.
   *
   * AUTHORITY 'none' IS NOT A CONCESSION, IT IS A REPETITION. The native
   * schedule_* tools require neither a turn nor human authority: the only check
   * inside is agent identity (exec.agent !== agent → internalError). Tightening
   * that here would break work exactly as much as loosening it.
   *
   * THEY ARE NOT UNDER THE CEILING: the ceiling counts GOAL creation, and a
   * reminder creates no goal. Schedule has a limit of its own, and it is theirs:
   * the package itself enforces no more often than five minutes.
   */
  schedule_create: { authority: 'none', native: true, guard: heartbeatGuard },
  schedule_list: { authority: 'none', native: true },
  schedule_delete: { authority: 'none', native: true },
}

/**
 * Call the native body of a tool registered on the live agent.
 *
 * 🔴 WHY NOT registry.execute(), BUT THE DEFINITION DIRECTLY. registry.execute
 * runs the call through the tools/pre-execute waterfall — that is, through
 * asking the user for permission. On our layout there is no answerer, and the
 * policy fails closed: the tool would refuse ALWAYS, and it would look like
 * "the schedule is broken". Besides, registry.execute materialises the result
 * into content blocks, while the bridge needs JSON. The tool body itself is
 * wrapped by the platform (defineTool): schema validation of arguments, the
 * ToolArgsError refusal and the agent-identity check are all inside, and the
 * bridge repeats none of it.
 *
 * WHAT WE LOSE BY DOING SO, SAID PLAINLY: the call time limit (timeoutMs), the
 * registry's concurrency queue and cancellation by the turn signal. For the
 * three schedule tools that is nothing: they declare no timeoutMs, their bodies
 * are serialised by their own transaction, and the bridge cannot provide
 * cancellation — loopback HTTP knows nothing of the turn signal. We pass an
 * honest non-cancellable signal: a fake "already cancelled" would turn every
 * call into a silent refusal.
 *
 * A MISSING DEFINITION IS BLINDNESS, NOT A REFUSAL. If the tool is not
 * registered on the agent, then the schedule layer is not mounted, or the agent
 * is the wrong one. We shout about it on its own line: a silent "not found" is
 * read by the model as "nothing to schedule", and we would be hunting the
 * defect in the schedule instead of in the mounting.
 */
async function nativeCall(ctx, agent, toolName, args) {
  const registry = ctx.get('tools')
  if (!registry || typeof registry.get !== 'function') {
    throw new Error('the platform tool registry is unavailable — the native path cannot run')
  }
  // get(name, scope) — "how THIS agent sees the tool". The scope is what
  // matters: schedule is registered in the scope of a SPECIFIC agent, and a
  // definition taken without it would belong to a different closure — that is,
  // it would refuse on agent identity.
  const def = registry.get(toolName, agent)
  if (!def || typeof def.execute !== 'function') {
    log(`🔴 BLINDNESS: "${toolName}" is not registered on agent ${agent?.id ?? '?'} — the layer is not mounted`)
    throw new Error(`"${toolName}" is not registered on the live agent: the platform layer is not mounted`)
  }
  return await def.execute(args, { agent, signal: new AbortController().signal })
}

/** Is a text argument meaningful — verbatim hasText from dsh-tool-goal. */
const hasText = (v) => v !== undefined && v !== ''
/** Is a round cap meaningful — verbatim hasRoundCap: zero here is a schema filler. */
const hasRoundCap = (v) => v !== undefined && v !== 0

/**
 * update_goal — one name, five actions, and that is the native route's shape,
 * not ours. Each action has its own authority, copied verbatim from
 * dsh-tool-goal: edit/pause/resume — direct human turn only; complete/blocked —
 * a human OR the current goal round.
 *
 * 🔴 THE ONLY MUTATING ACTION THAT BYPASSES THE BOUNDARY IS blocked: the block
 * method is not marked Remote in dsh-goal, so it does not exist from outside.
 * That means the check the boundary performs for the other actions is repeated
 * here by the host.
 *
 * 🔴 THE blocked THRESHOLD APPLIES ONLY UNDER ROUND AUTHORITY. In the original
 * the condition includes authority.kind === "goal-round": the threshold guards
 * against an agent giving up on itself at the first self-wake, and nothing else.
 * In a human turn the block goes through immediately, at round zero. The first
 * version of this bridge applied the threshold ALWAYS — that is, a human could
 * not get the answer "I am stuck". Home-grown tightening breaks work as much as
 * loosening does; fixed 2026-08-22 on an operational correction.
 */
async function updateGoal(ctx, agents, agentId, a, limits) {
  const execution = bridgeExecution(agents, agentId)
  const ref = { id: String(a.goal_id), revision: a.revision }
  const action = a.action

  if (action === 'edit') {
    requireDirectHuman(agents, execution)
    if (hasText(a.blocked_reason)) throw new Error('blocked_reason is allowed only with action blocked')
    const capped = capRounds(ctx, hasRoundCap(a.max_goal_rounds) ? a.max_goal_rounds : undefined)
    const request = {
      ...(hasText(a.objective) ? { objective: a.objective } : {}),
      ...(capped === undefined ? {} : { maxGoalRounds: capped }),
    }
    return remoteCall(ctx, 'goals', 'edit', { ref, request }, agentId)
  }

  if (action === 'pause' || action === 'resume') {
    requireDirectHuman(agents, execution)
    if (hasText(a.objective) || hasRoundCap(a.max_goal_rounds) || hasText(a.blocked_reason)) {
      throw new Error('objective and max_goal_rounds are allowed only with action edit; blocked_reason only with blocked')
    }
    return remoteCall(ctx, 'goals', action, { ref }, agentId)
  }

  if (action !== 'complete' && action !== 'blocked') {
    throw new Error(`unknown action "${action}"`)
  }

  const authority = completionAuthority(ctx, agents, execution)
  if (hasText(a.objective) || hasRoundCap(a.max_goal_rounds)) {
    throw new Error('objective and max_goal_rounds are allowed only with action edit')
  }
  if (action === 'complete') {
    if (hasText(a.blocked_reason)) throw new Error('blocked_reason is allowed only with action blocked')
    return remoteCall(ctx, 'goals', 'complete', { ref }, agentId)
  }

  const reason = typeof a.blocked_reason === 'string' ? a.blocked_reason.trim() : ''
  if (!reason) throw new Error('blocked_reason is required with action blocked')
  if (authority.kind === 'goal-round' && authority.goal.roundsStarted < limits.blockedAfterRounds) {
    throw new Error(
      `blocked requires at least ${limits.blockedAfterRounds} consecutive autonomous rounds; `
      + `${authority.goal.roundsStarted} have started so far`,
    )
  }
  return ctx.get('goals').block(execution.agent, ref, { code: 'model-reported', message: reason })
}

/**
 * The only place where identity reaches the wire.
 * 🔴 KEY ORDER MATTERS: identity comes AFTER the arguments. In the opposite
 * order a build() that passed the model's arguments through would silently
 * overwrite the identity — that is, the model would be assigning it itself.
 */
function remoteCall(ctx, namespace, method, args, agentId) {
  return ctx.get('typertGateway').invoke({
    namespace,
    method,
    args: { ...args, agentId: String(agentId) },
  })
}

/**
 * 🔴 THE GOAL-CREATION CEILING (an operational decision).
 *
 * WHY. The round limit is PER GOAL, not per agent: close a goal, create a new
 * one, and the round counter starts over. So the creation tool is able to
 * bypass the limit from inside and produce an unbounded runaway. Engine
 * subagents are invisible to the platform and arrive with the root's identity,
 * with nothing to tell them apart (verified 2026-08-22: BUILT-IN subagent types
 * cannot have the bridge server taken away) — therefore the limit sits not at
 * the model but here, on our side of the wire. Neither the model nor a subagent
 * can reach this far: they see only a tool name and its schema.
 *
 * WHAT IT PROTECTS AGAINST: a loop the mechanism entered by itself, a bug in
 * the code, an avalanche of retries.
 * WHERE IT DOES NOT APPLY: it is no protection against a deliberate act by an
 * agent with full sudo, and does not claim to be — the counter lives in the
 * memory of the platform process, and that process is mine.
 * IT NEVER OBSTRUCTS CLOSING A GOAL: only creation is under the ceiling, and
 * that is not a caveat but the design — the other tools do not touch the counter.
 * IT IS RESET BY A PLATFORM RESTART: the state is in memory and is not written
 * to disk.
 * IT REPAIRS NOTHING BY ITSELF: on hitting the ceiling it refuses and writes a
 * log line; there are no other actions.
 *
 * 🔴 WHAT THE COUNTER IS KEYED BY (an operational requirement, check this first).
 * The key is THE IDENTITY OF THE LIVE AGENT, which the host obtains by itself:
 *   provider adapter → ctx.get('agents').currentInitiator().id → the bridge
 *   issues a ONE-TIME TICKET for that identity → the request body to the gateway
 *   carries the ticket, not the identity → the gateway keeps the ticket in the
 *   server CLOSURE → presents it at the door → the bridge looks into its own
 *   table and retrieves the identity.
 *   The model takes no part anywhere in this chain, and identity is NOT ON THE
 *   WIRE AT ALL.
 * NOT from the tool arguments: the bridge reads neither identity, nor owner, nor
 * session from args — there are only subject fields there (objective, goal id,
 * revision).
 * NOT by the ENGINE session id: that one is born in the gateway on every request
 * (crypto.randomUUID), and there would be no counter at all — every call would
 * produce a new key.
 * AN HONEST CAVEAT: the key's value COINCIDES with the PLATFORM session id — for
 * the platform that is an invariant (agent.id === agent.session.id, checked with
 * a throw in dsh-agent enter()). The difference is not in the value but in the
 * source: it is taken from the registry of live agents, not from the body. There
 * is nothing to bypass it with by switching sessions: platform sessions are
 * created only by the channel module, keyed <channel>-<id>, so a new session is
 * a new chat, which a human starts, not the model.
 * ENGINE SUBAGENTS fall into the ROOT's counter: they inherit the root's server
 * instance, and the identity lies in its closure. A hole that cannot be closed
 * (built-in types cannot be stripped of the server) works in our favour here.
 *
 * Counted per session identity, not machine-wide: every agent has its own ceiling.
 */
const creations = new Map()

/**
 * Reserve a slot for creating a goal. The slot is taken BEFORE the call and
 * released if the call fails — otherwise two concurrent calls would both pass
 * the check, each seeing state the other had not written yet.
 */
function reserveCreate(agentId, limit, windowMs, now) {
  const kept = (creations.get(agentId) ?? []).filter((t) => now - t < windowMs)
  if (kept.length >= limit) {
    creations.set(agentId, kept)
    return { allowed: false, used: kept.length }
  }
  kept.push(now)
  creations.set(agentId, kept)
  return { allowed: true, used: kept.length }
}

/** Release a taken slot: the call failed, no goal was created. */
function releaseCreate(agentId, now) {
  const kept = (creations.get(agentId) ?? []).filter((t) => t !== now)
  creations.set(agentId, kept)
}

/**
 * 🔴 WAKE-UPS ARE COUNTED FROM THE SESSION LOG, NOT FROM MEMORY. THIS IS LOAD-BEARING.
 *
 * The operational requirement read "the counter must survive a platform
 * restart, otherwise a restart resets the protection". It is met NOT by storage
 * but by construction: there is no counter at all, it is DERIVED from
 * agent.session.events — the very log the schedule restores itself from. There
 * is nothing for a restart to reset: the hole has structurally nowhere to appear.
 *
 * That events do come back from disk into agent.session.events is not an
 * assumption but a measurement from 2026-08-22: reminder schedule-2, set before
 * a platform restart (PID 1874902 -> 1885447 at 19:26:20), fired after it with a
 * deviation of 1 ms over 900 s, and the seq numbering in the log continued
 * instead of resetting to zero.
 *
 * THE SIGN OF AN AUTONOMOUS TURN was read off a live log, not invented:
 *     turn/end -> agent/inbox/spliced -> schedule/change(dispatch) -> turn/start
 * against a human one:
 *     turn/end -> agent/inbox/spliced -> turn/start -> user/message(kind=<kind>)
 * 🔴 The naive check "was there a message from a human" DOES NOT WORK: a
 * reminder and a letter arrive identically — through agent/inbox/spliced with
 * role user. Exactly one thing tells them apart: whether there is a dispatch
 * BETWEEN the previous turn/end and this turn/start. That is why the flag is
 * cleared both on turn/start (spent) and on turn/end (a dispatch in the middle
 * of somebody else's turn woke nobody and does not count).
 */

/**
 * Message kinds that count as a word from a human and break the streak.
 *
 * 🔴 THIS IS A SETTING, NOT A CONSTANT, AND HERE IS WHY. The kind 'user' is the
 * platform's — everyone has it. Any other kind is introduced by whichever module
 * receives messages: on our installation the service channel between agents
 * arrives with its own kind, and it too is a word from a live human. Had we
 * hard-coded this list, on somebody else's build only one kind out of two would
 * break the streak — and SILENTLY: a superfluous wake-up is indistinguishable
 * from an honest one.
 *
 * 🔴 AND SEPARATELY: goal authority has its own, DIFFERENT list — there a service
 * kind does NOT grant human rights. This is not inconsistency. There the question
 * is "may a service channel dispose of the goal", here it is "is anybody alive
 * nearby". Different questions, different answers; changing one without touching
 * the other is legitimate.
 */
const HEARTBEAT_HUMAN_KINDS_DEFAULT = ['user']

/** A ledger of the session's turns: what started each one. Event order matters. */
function turnLedger(events, humanKinds) {
  const turns = []
  let dispatched = false
  let current
  for (const e of events) {
    const t = e?.type
    if (t === 'schedule/change') {
      if (e.data?.operation === 'dispatch') dispatched = true
      continue
    }
    if (t === 'turn/start') {
      current = { turn: e.data?.turn, autonomous: dispatched, human: false }
      turns.push(current)
      dispatched = false
      continue
    }
    if (t === 'turn/end') { current = undefined; dispatched = false; continue }
    if (t === 'user/message' && current !== undefined
      && humanKinds.has(e.data?.source?.kind)) current.human = true
  }
  return turns
}

/** The day key in the named zone. Through Intl rather than offset arithmetic:
 *  let the library, not us, work out daylight saving. */
function dayKeyFactory(zone) {
  const fmt = new Intl.DateTimeFormat('en-CA', {
    timeZone: zone, year: 'numeric', month: '2-digit', day: '2-digit',
  })
  return (ms) => fmt.format(ms)
}

/**
 * The streak of consecutive autonomous wake-ups and the count for the current day.
 * The streak is broken by ANY non-autonomous turn, not only a human one: a turn
 * that our reminder did not start spent no wake-up. Wake-ups from background
 * jobs do not appear here at all — they have their own limit (maxConsecutiveWakes).
 */
function heartbeatCounters(events, zone, now, humanKinds) {
  const turns = turnLedger(events, humanKinds)
  let streak = 0
  for (let i = turns.length - 1; i >= 0; i -= 1) {
    const t = turns[i]
    if (t.human || !t.autonomous) break
    streak += 1
  }
  const dayKey = dayKeyFactory(zone)
  const today = dayKey(now)
  let perDay = 0
  for (const e of events) {
    if (e?.type === 'schedule/change' && e.data?.operation === 'dispatch'
      && dayKey(e.time) === today) perDay += 1
  }
  return { streak, perDay, turns: turns.length }
}

/**
 * The check performed when a RECURRING reminder is CREATED.
 * 🔴 A DEPARTURE FROM THE RULE "the bridge does not execute schedule, it only
 * delivers" — said out loud. There is exactly one policy of ours on top of
 * theirs, and this is it: the interval. One-shot reminders (after_seconds / at)
 * are NOT TOUCHED by it — they have no interval.
 */
function heartbeatGuard(args, limits) {
  const every = args?.every_seconds
  if (every === undefined) return
  if (typeof every === 'number' && every >= limits.heartbeatMinIntervalSeconds) return
  throw new Error(
    `a recurring reminder may run no more often than once every ${limits.heartbeatMinIntervalSeconds} s — `
    + `this is a host limit, not an error (requested ${every}). The platform minimum of 300 s comes from a different problem: `
    + 'it is meant for short supervised work cycles, whereas background self-waking every five minutes is 288 turns a day. '
    + 'If you need a tighter cycle, it must run under human supervision, not on an alarm clock.',
  )
}

/**
 * Stop the cycle and say so. The order is exactly this: FIRST the stop, then the
 * notice. Stopping matters more than notifying — but silence is not allowed in
 * any outcome, so the notice is written even when the stop failed, and then it
 * will have to be finished by hand.
 */
async function stopHeartbeat(ctx, agent, why, counters, limits, rootCount) {
  const sid = String(agent?.id ?? '?')
  const removed = []
  let failure
  try {
    const list = await nativeCall(ctx, agent, 'schedule_list', {})
    if (!Array.isArray(list)) throw new Error(`schedule_list returned a non-list: ${JSON.stringify(list).slice(0, 200)}`)
    for (const rec of list) {
      // 🔴 WE REMOVE ALL ACTIVE ONES, NOT ONLY THE RECURRING ONES. This follows
      // from counting WAKE-UPS rather than rule types: a chain in which every
      // self-wake sets itself a fresh one-shot alarm bypasses the limit in one
      // line. So one-shots are removed as well — but every one of them is named
      // by id in the log and in the notice, so that nothing disappears silently.
      const r = await nativeCall(ctx, agent, 'schedule_delete', { id: rec.id })
      removed.push(`${rec.id} (${rec.kind}${rec.everySeconds === undefined ? '' : `, every ${rec.everySeconds} s`})`
        + ` — ${r?.deleted ? 'removed' : `NOT removed: ${r?.code ?? '?'}`}`)
    }
  } catch (e) {
    failure = String(e?.message ?? e)
    log(`🔴 self-wake limit: stopping for ${sid} FAILED: ${failure}`)
  }
  log(`🔴 self-wake limit for ${sid}: ${why}; reminders removed ${removed.length}`
    + (removed.length ? `: ${removed.join('; ')}` : ''))

  const text = [
    `[stop limit] session ${sid}`,
    '',
    `Stopped on the self-wake limit: ${why}.`,
    `Counted from the session log: autonomous wake-ups in a row ${counters.streak} `
      + `(limit ${limits.heartbeatMaxConsecutive}), for the current day ${counters.perDay} `
      + `(limit ${limits.heartbeatMaxPerDay} PER SESSION, zone ${limits.heartbeatDayZone}).`,
    `🔴 The limit of 48 a day is PER SESSION, not per agent. Live root sessions right now: ${rootCount}, `
      + `so the agent's total ceiling is ${rootCount * limits.heartbeatMaxPerDay} wake-ups a day.`,
    '',
    removed.length
      ? `Active reminders removed: ${removed.length}: ${removed.join('; ')}.`
      : 'There were no active reminders at the moment of stopping — nothing to remove.',
    failure === undefined
      ? ''
      : `🔴 STOPPING FAILED: ${failure}. Reminders may still be alive — remove them by hand.`,
    '',
    'What was done during the streak is in my reports and in the session log. I will continue on your word.',
  ].filter((l) => l !== '').join('\n')

  if (limits.heartbeatNoticeDir === '') {
    // No directory set — that is a configured outcome, not a loss. But the text
    // of the notice must still be spoken in full: silence is indistinguishable
    // from a breakage.
    log(`self-wake limit: no notice directory configured, full notice to the log: ${text.replace(/\n/g, ' | ')}`)
    return
  }
  try {
    mkdirSync(limits.heartbeatNoticeDir, { recursive: true })
    const file = `${limits.heartbeatNoticeDir}/${Date.now()}-heartbeat-limit.txt`
    writeFileSync(file, `${text}\n`)
    log(`self-wake limit: notice to the owner written to ${file}`)
  } catch (e) {
    // 🔴 WE DO NOT CRASH. The cycle is already stopped, and that is the main
    // thing; but we do not stay silent either — silence here is
    // indistinguishable from a breakage. The whole notice goes to the log.
    log(`🔴 self-wake limit: the notice was NOT WRITTEN to ${limits.heartbeatNoticeDir} (${e?.message ?? e}). Full text: ${text.replace(/\n/g, ' | ')}`)
  }
}

/** One shared handler for both local and remote tools. */
async function callTool(ctx, agents, toolName, agentId, args, limits) {
  const exec = EXEC[toolName]
  if (!exec) throw new Error(`tool "${toolName}" is not exposed by the bridge`)

  // 🔴 AUTHORITY IS CHECKED FIRST — before the ceiling. A refusal on rights must
  // not occupy a slot in the creation counter: otherwise an unauthorised call
  // would spend somebody else's ceiling. Each tool has its own level, copied
  // from the original:
  //   none     — like job_* on the native route: a live agent only, no turn required;
  //   turn     — like get_goal: a live agent and an open turn, no authority;
  //   human    — like create_goal: plus a direct human turn on the root;
  //   dispatch — like update_goal: authority depends on the action, see updateGoal.
  let execution
  if (exec.authority === 'turn' || exec.authority === 'human') {
    execution = bridgeExecution(agents, agentId)
    if (exec.authority === 'human') requireDirectHuman(agents, execution)
  }

  // Our own limit is checked after rights and before the platform, for the same
  // reason: a refusal must cost zero calls into it. There is one guard right
  // now, and it is on the interval of a recurring reminder (see heartbeatGuard).
  if (exec.guard) exec.guard(args, limits)

  // The ceiling is checked after rights but before the platform: a refusal must
  // cost zero calls into it.
  let reserved
  if (exec.counted) {
    const now = Date.now()
    const r = reserveCreate(agentId, limits.createLimit, limits.createWindowMs, now)
    // 🔴 Every creation is a log line, both the allowed and the refused one. A
    // silent refusal is inadmissible here: the cycle would simply not start and
    // we would be guessing why. The session identity in the line is mandatory —
    // otherwise it is invisible whose it was.
    if (!r.allowed) {
      log(`🔴 goal creation: session=${agentId} — REFUSED, ceiling ${limits.createLimit} per ${limits.createWindowMs / 60000} min exhausted (${r.used} taken)`)
      throw new Error(
        `the goal-creation ceiling is exhausted: ${limits.createLimit} per ${limits.createWindowMs / 60000} min. ` +
        'This is a host limit, not an error: it frees up as old entries leave the window. ' +
        'There is nothing to bypass it with and no need to — work on the goal you already have, or wait for the window.',
      )
    }
    reserved = now
    log(`goal creation: session=${agentId} — allowed (${r.used} of ${limits.createLimit} taken per ${limits.createWindowMs / 60000} min)`)
  }

  try {
    if (exec.dispatch) return await exec.dispatch(ctx, agents, agentId, args, limits)
    if (exec.remote) return await remoteCall(ctx, exec.remote.namespace, exec.remote.method, exec.remote.build(args, ctx), agentId)

    // The local path. We look the live agent up in the registry by the same
    // identity the boundary uses; not found — a refusal, not silence: otherwise
    // reading somebody else's session would look like "there is no goal".
    // agents.get(id) — "Look up a live agent", returns undefined if no live
    // agent has that id. Live specifically: that is the same sign the remote
    // boundary's refusal rests on, so the local path is no softer than the
    // remote one.
    const agent = execution?.agent ?? agents.get(String(agentId))
    if (!agent) throw new Error(`live agent "${agentId}" not found in the registry`)
    // The native path requires the same live agent and for the same reason:
    // without it the schedule would be written into somebody else's session, or
    // not written at all.
    if (exec.native) return await nativeCall(ctx, agent, toolName, args)
    return await exec.local(ctx, agent, args)
  } catch (e) {
    if (reserved !== undefined) {
      releaseCreate(agentId, reserved)
      log(`goal creation: session=${agentId} — failed, slot released`)
    }
    throw e
  }
}

/**
 * 🔴 ONE ENTRY POINT PER PROCESS. cordis calls apply on every rebuild of the
 * plugin set, and the instances stay alive: without this flag one more
 * listening socket would come up per mount (four were observed). It is cleared
 * on dispose — a legitimate remount still works.
 */
let mounted = false

export function apply(ctx, config) {
  if (mounted) {
    log('repeated mount while the entry point is alive — skipping')
    return
  }
  mounted = true
  /**
   * 🔴 A ONE-TIME TICKET INSTEAD OF IDENTITY ON THE WIRE (an operational design).
   * There is NO identity at our door at all: the gateway carries an opaque
   * random string and knows nothing about goals or agents. The platform knows
   * the identity — and it is the platform that substitutes it, looking into its
   * own table. The difference is fundamental: previously the caller ASSERTED the
   * identity (whoever reached the door and knew the secret could call themselves
   * anyone), now it is ISSUED by the one who knows it.
   * The ticket doubles as the secret: it is random (24 bytes of crypto), so
   * there is no separate door secret any more — one field instead of two.
   *
   * THE TICKET IS BOUND TO A TURN, NOT TO AN AGENT. This is a fix: the earlier
   * revision kept one ticket per identity and revoked the previous one when
   * issuing a new one — and concurrent turns of one agent DO HAPPEN here
   * (on 2026-08-21 an interrupted turn lived for five minutes alongside a new
   * one and edited the same files). Back then a new turn silently took the tools
   * away from the live earlier one.
   *
   * BOUNDARIES, without which the protection turns into its own opposite:
   *  • ONE TICKET PER (identity, turn). Two concurrent turns are two different
   *    tickets, and revoking one does not touch the other.
   *  • IT DIES AT THE END OF ITS OWN TURN, any end: the platform writes turn/end
   *    both on a normal finish and on an abort (interruptedTurnClosers appends
   *    an interrupted turn/end when restoring the log).
   *  • AN UPPER LIFETIME AS A NUMBER — for the case where turn/end never arrives
   *    at all (the process dies before the write). Without it "one-time" would
   *    degenerate into "lives as long as the process", that is, into a
   *    long-lived password.
   *  • ROOT AGENTS ONLY. A platform subagent would receive its own ticket with
   *    its own identity — that is, its own goal-creation counter, and the
   *    ceiling would be bypassed by way of the boundary. There are no platform
   *    subagents at all right now (agents are created only by the channel
   *    module), so the check is free and stops their appearance from quietly
   *    widening rights. ENGINE subagents are unaffected: they have no separate
   *    call to the gateway, they work inside the root's turn and carry its
   *    ticket — and their creations land in the root's counter.
   *  • THE TICKET IS NOT WRITTEN TO DISK, TO THE LOG OR TO THE ENVIRONMENT. It
   *    lives in the platform's memory and in the closure of the gateway handler;
   *    with the sdk transport nothing goes into a command line (measured: 0 hits
   *    across 275 inspected processes). Log lines carry only identity and turn.
   *  • WHAT IT DOES NOT PROTECT AGAINST: reading the process memory, and anyone
   *    with root. The ticket has no OS rights; all that guards it is that it is
   *    written down nowhere.
   */
  const TICKET_TTL_MS = (config?.ticketTtlMinutes ?? TICKET_TTL_MINUTES_DEFAULT) * 60000
  /** ticket → { agentId, turn, issuedAt } */
  const tickets = new Map()
  /**
   * `identity#turn` → the SET of live tickets of that turn.
   * 🔴 A set, precisely, not a single one. Within ONE platform turn more than
   * one request goes to the provider (the turn itself and, for example,
   * generating the session header), and each asks for its own bridge
   * descriptor. While there was a single ticket, the second request revoked the
   * first one's ticket — which had already gone to the engine, so the model got
   * "ticket unknown or already revoked" at the door in the middle of a live turn
   * (run at 10:57, turn 1). One-time-ness is held at the level of the TURN:
   * turn/end revokes all tickets of that turn at once.
   */
  const ticketOf = new Map()
  /** identity → the number of the open turn; maintained from session events */
  const openTurnOf = new Map()

  const turnKey = (agentId, turn) => `${agentId}#${turn ?? '-'}`

  /** Drop the expired ones. Called on issue: a separate timer here would be a
   *  mechanism without a stop condition, for the sake of two map entries. */
  const dropExpired = () => {
    const now = Date.now()
    for (const [t, rec] of tickets) {
      if (now - rec.issuedAt <= TICKET_TTL_MS) continue
      tickets.delete(t)
      const set = ticketOf.get(turnKey(rec.agentId, rec.turn))
      if (set) { set.delete(t); if (!set.size) ticketOf.delete(turnKey(rec.agentId, rec.turn)) }
    }
  }

  const issueTicket = (agentId, turn) => {
    dropExpired()
    const key = turnKey(agentId, turn)
    // Earlier tickets of THIS SAME turn are NOT revoked: they may already be
    // with the engine (see the note on ticketOf). They all die with the turn.
    const ticket = randomBytes(24).toString('hex')
    tickets.set(ticket, { agentId, turn, issuedAt: Date.now() })
    let set = ticketOf.get(key)
    if (!set) { set = new Set(); ticketOf.set(key, set) }
    set.add(ticket)
    log(`ticket issued: ${agentId} turn ${turn ?? '-'}; live tickets of this turn ${set.size}`)
    return ticket
  }

  /** Revoke the tickets of a finished turn. */
  const revokeTurn = (agentId, turn) => {
    const key = turnKey(agentId, turn)
    const set = ticketOf.get(key)
    if (!set || !set.size) return false
    for (const t of set) tickets.delete(t)
    const n = set.size
    ticketOf.delete(key)
    return n
  }

  /**
   * Returns the identity for a ticket, or the reason for refusal. We fail
   * CLOSED: an unknown, revoked or expired ticket is a refusal with a clear
   * reason, not an empty identity passed off as success.
   */
  const resolveTicket = (ticket) => {
    if (typeof ticket !== 'string' || !ticket) return { error: 'no ticket presented' }
    const rec = tickets.get(ticket)
    if (!rec) return { error: 'ticket unknown or already revoked' }
    if (Date.now() - rec.issuedAt > TICKET_TTL_MS) {
      tickets.delete(ticket)
      const set = ticketOf.get(turnKey(rec.agentId, rec.turn))
      if (set) { set.delete(ticket); if (!set.size) ticketOf.delete(turnKey(rec.agentId, rec.turn)) }
      return { error: 'ticket expired' }
    }
    return { agentId: rec.agentId }
  }

  // A turn opened / closed. The number of the open turn is needed to bind a
  // ticket to it; turn/end revokes the tickets of exactly its own turn.
  ctx.on('session/event', (session, event) => {
    const sid = String(session?.id ?? '')
    if (!sid) return
    if (event?.type === 'turn/start') openTurnOf.set(sid, event.data?.turn)
    else if (event?.type === 'turn/end') {
      if (openTurnOf.get(sid) === event.data?.turn) openTurnOf.delete(sid)
      const n = revokeTurn(sid, event.data?.turn)
      if (n) {
        log(`tickets of turn ${event.data?.turn} for ${sid} revoked: ${n} (${event.data?.reason?.kind ?? 'end of turn'})`)
      }
      // Deferred, and kept clear of ticket revocation: an error in our own limit
      // has no right to deprive the turn of its normal ticket cleanup.
      // checkHeartbeat is declared BELOW in this file — it needs agents and
      // limits, which are assembled after this subscription. By the time the
      // first event arrives, apply has long finished, so the forward reference
      // resolves.
      setTimeout(() => {
        checkHeartbeat(sid).catch((e) => log(`🔴 self-wake limit: the check for ${sid} threw: ${e?.message ?? e}`))
      }, 0)
    }
  })

  const agents = ctx.get('agents')
  const limits = {
    createLimit: config?.createLimit ?? CREATE_LIMIT_DEFAULT,
    createWindowMs: (config?.createWindowMinutes ?? CREATE_WINDOW_MINUTES_DEFAULT) * 60000,
    blockedAfterRounds: config?.blockedAfterRounds ?? BLOCKED_AFTER_ROUNDS_DEFAULT,
    serverName: config?.serverName ?? SERVER_NAME_DEFAULT,
    heartbeatMinIntervalSeconds: config?.heartbeatMinIntervalSeconds ?? HEARTBEAT_MIN_INTERVAL_SECONDS_DEFAULT,
    heartbeatMaxConsecutive: config?.heartbeatMaxConsecutive ?? HEARTBEAT_MAX_CONSECUTIVE_DEFAULT,
    heartbeatMaxPerDay: config?.heartbeatMaxPerDay ?? HEARTBEAT_MAX_PER_DAY_DEFAULT,
    heartbeatDayZone: config?.heartbeatDayZone ?? HEARTBEAT_DAY_ZONE_DEFAULT,
    heartbeatNoticeDir: config?.heartbeatNoticeDir ?? HEARTBEAT_NOTICE_DIR_DEFAULT,
    heartbeatHumanKinds: new Set(config?.heartbeatHumanKinds ?? HEARTBEAT_HUMAN_KINDS_DEFAULT),
  }

  /**
   * 🔴 THE LIMIT IS CHECKED AT THE END OF A TURN, AND THAT IS A BOUNDARY, NOT A
   * CONVENIENCE. The operational requirement: "the limit stops the CYCLE but
   * does not touch a turn already started — unfinished work is not aborted".
   * turn/end means the turn is finished; stopping earlier is dishonest, and
   * later there is nothing to stop on.
   *
   * THE MOUNTING POINT WAS TAKEN ALREADY PROVEN. In the design I named
   * agent/status and said I had not checked it live. Checking turned out to be
   * unnecessary: this same plugin has been holding ticket revocation on
   * session/event since 2026-08-21, so the subscription demonstrably reaches us
   * at this very mounting point. A new mounting point next to a working one is a
   * superfluous entity.
   *
   * DEFERRED WITH setTimeout(0) DELIBERATELY. The platform publishes the event
   * SYNCHRONOUSLY and holds a lock while publishing: "session append cannot
   * reenter while another append is being published" (dsh-session,
   * lib/index.js:1456). Stopping writes to the log (schedule/change delete) —
   * that is, it cannot be called from inside the event handler. A deferred call
   * lands outside the publication.
   */
  const stopped = new Set()
  const checkHeartbeat = async (sid) => {
    const agent = agents.get(sid)
    if (!agent) return
    // Root agents only: a subagent has no schedule of its own, and the streak is
    // counted from the root's log. The same boundary as for the ticket.
    if (typeof agents.roots !== 'function' || !agents.roots().includes(agent)) return
    const c = heartbeatCounters(agent.session.events, limits.heartbeatDayZone, Date.now(),
      limits.heartbeatHumanKinds)
    const overStreak = c.streak >= limits.heartbeatMaxConsecutive
    const overDay = c.perDay >= limits.heartbeatMaxPerDay
    // A line on EVERY end of turn. A mechanism that says nothing is
    // indistinguishable from a switched-off one — we have already been through
    // that with persistence.
    log(`self-wake ${sid}: in a row ${c.streak}/${limits.heartbeatMaxConsecutive}, `
      + `per day ${c.perDay}/${limits.heartbeatMaxPerDay} (zone ${limits.heartbeatDayZone})`)
    if (!overStreak && !overDay) {
      // 🔴 THE CONDITION THAT REARMS THE GUARD, without which it would fire once
      // in the lifetime of the process: the streak was broken by a human, or a
      // new day has begun.
      if (stopped.delete(sid)) log(`self-wake limit: the streak for ${sid} is broken — the guard is armed again`)
      return
    }
    // Once per streak, not once per turn: a stop notice repeated on every turn
    // would itself become the noise the limit protects against.
    if (stopped.has(sid)) return
    stopped.add(sid)
    const why = overStreak
      ? `${c.streak} autonomous wake-ups in a row without a word from a human (limit ${limits.heartbeatMaxConsecutive})`
      : `${c.perDay} wake-ups in a day in this session (limit ${limits.heartbeatMaxPerDay})`
    await stopHeartbeat(ctx, agent, why, c, limits, agents.roots().length)
  }

  const server = createServer(async (req, res) => {
    const reply = (code, body) => {
      res.writeHead(code, { 'content-type': 'application/json; charset=utf-8' })
      res.end(JSON.stringify(body))
    }
    if (req.method !== 'POST' || req.url !== '/invoke') return reply(404, { ok: false, error: 'only POST /invoke exists' })
    const pass = resolveTicket(req.headers['x-bridge-ticket'])
    if (pass.error) {
      log(`\u{1F534} refused at the door: ${pass.error}`)
      return reply(403, { ok: false, error: pass.error })
    }

    let payload
    try {
      const chunks = []
      for await (const c of req) chunks.push(c)
      payload = JSON.parse(Buffer.concat(chunks).toString('utf8'))
    } catch { return reply(400, { ok: false, error: 'body could not be parsed' }) }

    try {
      const value = await callTool(ctx, agents, payload.tool, pass.agentId, payload.args ?? {}, limits)
      // Every call is a log line. It is the sign that the bridge is alive and
      // that the call actually reached it: without it, "the model did not call
      // the tool" and "the tool did not arrive" look identical.
      log(`call ${payload.tool} for ${pass.agentId}: success`)
      reply(200, { ok: true, value })
    } catch (e) {
      // The reason goes back out: a silent tool refusal is read by the model as
      // "the tool is broken", and it starts looking for a way around.
      log(`🔴 ${payload?.tool} for ${pass.agentId}: ${e?.message}`)
      reply(200, { ok: false, error: String(e?.message ?? e).slice(0, 500) })
    }
  })

  let port
  server.listen(config.port, '127.0.0.1', () => {
    port = server.address().port
    // 🔴 The numbers in the line are mandatory, and so is the mark saying where
    // they came from: our values coincide with the defaults, so a bare number
    // does not tell "the config arrived" from "the field was lost".
    const src = (k) => (config?.[k] === undefined ? 'default' : 'configured')
    // Two counts apart rather than one total: the layers differ in origin and in
    // execution, and the loss of a whole layer must be visible in the startup line.
    log(`entry point 127.0.0.1:${port}; tools ${TOOLS.length}`
      + ` (parity with the native route ${PARITY.length}: ${PARITY.map((t) => t.name).join(', ')};`
      + ` platform schedule ${SCHEDULE.length}: ${SCHEDULE.map((t) => t.name).join(', ')})`)
    log(`goal-creation ceiling: ${limits.createLimit} (${src('createLimit')}) `
      + `per ${limits.createWindowMs / 60000} min (${src('createWindowMinutes')}); `
      + `under the ceiling: ${Object.entries(EXEC).filter(([, e]) => e.counted).map(([n]) => n).join(', ') || 'nothing'}`)
    log(`blocked threshold: ${limits.blockedAfterRounds} (${src('blockedAfterRounds')}) autonomous rounds`)
    log(`ticket: per (identity, turn), dies on turn/end; upper lifetime ${TICKET_TTL_MS / 60000} min (${src('ticketTtlMinutes')}); issued to root agents only`)
    log(`server name: "${limits.serverName}" (${src('serverName')}); the model sees the tools as mcp__${limits.serverName}__<name>`)
    // 🔴 Two lines, not one: the limit and its BOUNDARIES. A protection that does
    // not name where it does not apply will sooner or later produce exactly the
    // harm it was protecting against.
    // 🔴 The source mark is placed right after ITS OWN value, not as two words in
    // a row at the end: "(configured, configured)" keeps the meaning but does not
    // read — it is unclear whether the mark belongs to the number or to the zone.
    // There are still two sources.
    //
    // 🔴 The number 96 is printed as a written-out number on purpose. A stop
    // notice is read AFTER the event, whereas the startup line is read while
    // working out "what is actually configured"; a spoken "48 per session" would
    // be forgotten exactly as "per agent" would have been. It is computed from
    // the setting (×2) rather than typed in, so that it does not drift when the
    // limit changes.
    //
    // The live number of sessions is NOT taken here: an agent is created LAZILY,
    // on its first message, and at startup time agents.roots() is empty — on
    // 2026-08-22 the startup lines were at 22:55:55 and the agent was created at
    // 22:57:12, a gap of 77 seconds. The live number would always be 0 and would
    // lie. The live one is taken in the stop notice, where sessions already exist.
    log(`self-wake limit: no more often than ${limits.heartbeatMinIntervalSeconds} s (${src('heartbeatMinIntervalSeconds')}); `
      + `no more than ${limits.heartbeatMaxConsecutive} in a row without a word from a human (${src('heartbeatMaxConsecutive')}); `
      + `no more than ${limits.heartbeatMaxPerDay} per day PER SESSION, not per agent (${src('heartbeatMaxPerDay')}), `
      + `in zone ${limits.heartbeatDayZone} (${src('heartbeatDayZone')}); `
      + `the agent's total ceiling = number of live root sessions × ${limits.heartbeatMaxPerDay} `
      + `(two sessions already make ${2 * limits.heartbeatMaxPerDay} a day); `
      + `counted from the session log — a restart does not reset it; `
      + `a word from a human = source kinds [${[...limits.heartbeatHumanKinds].join(', ')}] (${src('heartbeatHumanKinds')}); `
      + `stop notice ${limits.heartbeatNoticeDir === '' ? 'to the log only: no directory configured' : `to ${limits.heartbeatNoticeDir}`} (${src('heartbeatNoticeDir')})`)
    log('self-wake limit DOES NOT APPLY: to goal rounds (they have their own defaultMaxGoalRounds), '
      + 'to wake-ups from background jobs (they have their own maxConsecutiveWakes), to an agent without the bridge '
      + '(on the native route the schedule runs on the native platform loop — it needs a guard of its own) '
      + 'and against anyone who has sudo: the isolation here is behavioural, and the counter is read from the log of my own process')
  })

  // The service is declared IMMEDIATELY rather than in the callback: cordis
  // requires provide before set, and the consumer must see the service from the
  // first moment. Until the port is taken, the descriptor is empty — and a line
  // is written about that, otherwise "there is no bridge" and "the bridge has
  // not come up yet" would look identical.
  ctx.provide('mcpBridge', {
    /** The server name — so that consumers do not assemble the prefix from memory. */
    serverName: limits.serverName,
    /**
     * The tool name AS THE MODEL SEES IT. The base name is literally the
     * platform's own; the prefix is added by the MCP protocol (exactly as for any
     * external MCP server). Needed by system prompts: text that names a tool
     * without the prefix sends the model to a name that does not exist.
     */
    modelToolName(base) { return `mcp__${limits.serverName}__${base}` },
    /** Base names of all exposed tools — for system prompts and checks. */
    toolNames() { return TOOLS.map((t) => t.name) },
    /**
     * A bridge descriptor for ONE turn of ONE identity. The identity is passed
     * in here by the host (the adapter takes it from the live initiator) and does
     * NOT LEAVE: the response contains only a ticket. Each call issues a new
     * ticket.
     */
    descriptor(agentId) {
      if (port === undefined) {
        log('🔴 a descriptor was requested before the entry point came up — tools are not connected')
        return undefined
      }
      if (typeof agentId !== 'string' || !agentId) {
        // Fail closed and loudly: a descriptor without an identity would mean a
        // ticket bound to nobody — that is, a door left wide open.
        log('🔴 a descriptor was requested without an identity — no ticket issued')
        return undefined
      }
      // 🔴 ROOT AGENTS ONLY. A platform subagent would receive its own ticket
      // with its own identity — that is, its own goal-creation counter, and the
      // ceiling would be bypassed by way of the boundary. The check is the same
      // one the platform makes in tool-goal: object identity, not name equality.
      const owner = agents?.get?.(agentId)
      if (!owner) {
        log(`🔴 descriptor for ${agentId}: no live agent with that identity — no ticket issued`)
        return undefined
      }
      if (typeof agents.roots === 'function' && !agents.roots().includes(owner)) {
        log(`🔴 descriptor for ${agentId}: the agent is not a root — no ticket issued`)
        return undefined
      }
      // The turn is taken from the map maintained by session events. There may be
      // no turn (the descriptor was requested outside a turn) — then the ticket
      // lives only until its deadline and no turn/end will revoke it; we mark
      // that with the key '-'.
      const turn = openTurnOf.get(agentId)
      return {
        // The server name is decided by the BRIDGE, not the gateway: the gateway
        // is generic, knows nothing about our domains, and its own default is a
        // generic word.
        name: limits.serverName,
        url: `http://127.0.0.1:${port}/invoke`,
        ticket: issueTicket(agentId, turn),
        // Schemas go to the model as JSON Schema: zod cannot travel over the
        // wire, and the gateway rebuilds it with its own adapter.
        // Names, descriptions and schemas come from parity.json and
        // schedule.json, that is, literally the ones the platform packages
        // register. The bridge hands them to the engine as they are.
        tools: TOOLS.map((t) => ({
          name: t.name,
          description: t.description,
          inputSchema: t.parameters,
        })),
      }
    },
  })

  ctx.on('dispose', () => {
    mounted = false
    try { server.close() } catch { /* the platform is shutting down, nobody to complain to */ }
  })
}
